[package]
name = "winter"
version = "0.0.1"
edition = "2021"

[dependencies]
anyhow = "1.0.69"
tracing-subscriber = { version = "0.3.17", features = ["env-filter"] }
windows = { path = "../windows" }
